In [18]:
import pandas as pd
pd.set_option('display.max_columns',39)
path = './dados.csv'
dados = pd.read_csv(path)
dados.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo   
0            0     Sim         Nao                1          Nao  \
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline   
0    SemServicoTelefonico               DSL             Nao          Sim  \
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato   
0                 Nao            Nao     Nao               Nao    Mensalmente  \
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

#variaveis categoricas
-agrupamento por caracteristicas em comum
-agrupamento por valores qualitativos

#variaveis numericas
-medida ou conjunto infinitos de valores

Maquinas aprende por números
Classificar= transformar as informaçções dos valores categóricos em algo que a máquina possa aprender

In [19]:
#modificação de forma manual
traducacao_dic = {
    'Sim':1,
    "Nao":0
}
dadosModificados = dados[['Conjuge','Dependentes','TelefoneFixo','PagamentoOnline','Churn']].replace(traducacao_dic)
dadosModificados.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

In [20]:
#transformação pelo get_dummies
dummie_dados = pd.get_dummies(dados.drop(['Conjuge','Dependentes','TelefoneFixo','PagamentoOnline','Churn'],axis=1))
dummie_dados = dummie_dados[['VariasLinhasTelefonicas_Nao','VariasLinhasTelefonicas_SemServicoTelefonico','VariasLinhasTelefonicas_Sim','ServicoDeInternet_DSL','ServicoDeInternet_FibraOptica','ServicoDeInternet_Nao','SegurancaOnline_Nao','SegurancaOnline_SemServicoDeInternet','SegurancaOnline_Sim','BackupOnline_Nao','BackupOnline_SemServicoDeInternet','BackupOnline_Sim','SeguroNoDispositivo_Nao','SeguroNoDispositivo_SemServicoDeInternet','SeguroNoDispositivo_Sim','SeguroNoDispositivo_Nao','SeguroNoDispositivo_SemServicoDeInternet','SeguroNoDispositivo_Sim','SuporteTecnico_Nao','SuporteTecnico_SemServicoDeInternet','SuporteTecnico_Sim','TVaCabo_Nao','TVaCabo_SemServicoDeInternet','TVaCabo_Sim','StreamingDeFilmes_Nao','StreamingDeFilmes_SemServicoDeInternet','StreamingDeFilmes_Sim','TipoDeContrato_DoisAnos','TipoDeContrato_Mensalmente','TipoDeContrato_UmAno','FormaDePagamento_CartaoDeCredito','FormaDePagamento_ChequeDigital','FormaDePagamento_ChequePapel','FormaDePagamento_DebitoEmConta']].replace({
    False:0,
    True:1
})
dummie_dados.head()



VariasLinhasTelefonicas_Nao  VariasLinhasTelefonicas_SemServicoTelefonico   
0                            0                                             1  \
1                            1                                             0   
2                            1                                             0   
3                            0                                             1   
4                            1                                             0   

   VariasLinhasTelefonicas_Sim  ServicoDeInternet_DSL   
0                            0                      1  \
1                            0                      1   
2                            0                      1   
3                            0                      1   
4                            0                      0   

   ServicoDeInternet_FibraOptica  ServicoDeInternet_Nao  SegurancaOnline_Nao   
0                              0                      0                    1  \
1                              0                      0                    0   
2                              0                      0                    0   
3                              0                      0                    0   
4                              1                      0                    1   

   SegurancaOnline_SemServicoDeInternet  SegurancaOnline_Sim   
0                                     0                    0  \
1                                     0                    1   
2                                     0                    1   
3                                     0                    1   
4                                     0                    0   

   BackupOnline_Nao  BackupOnline_SemServicoDeInternet  BackupOnline_Sim   
0                 0                                  0                 1  \
1                 1                                  0                 0   
2                 0                                  0                 1   
3                 1                                  0                 0   
4                 1                                  0                 0   

   SeguroNoDispositivo_Nao  SeguroNoDispositivo_SemServicoDeInternet   
0                        1                                         0  \
1                        0                                         0   
2                        1                                         0   
3                        0                                         0   
4                        1                                         0   

   SeguroNoDispositivo_Sim  SeguroNoDispositivo_Nao   
0                        0                        1  \
1                        1                        0   
2                        0                        1   
3                        1                        0   
4                        0                        1   

   SeguroNoDispositivo_SemServicoDeInternet  SeguroNoDispositivo_Sim   
0                                         0                        0  \
1                                         0                        1   
2                                         0                        0   
3                                         0                        1   
4                                         0                        0   

   SuporteTecnico_Nao  SuporteTecnico_SemServicoDeInternet   
0                   1                                    0  \
1                   1                                    0   
2                   1                                    0   
3                   0                                    0   
4                   1                                    0   

   SuporteTecnico_Sim  TVaCabo_Nao  TVaCabo_SemServicoDeInternet  TVaCabo_Sim   
0                   0            1                             0            0  \
1                   0            1                             0            0   
2                   0            1         

In [21]:
#junção dos dados transformados com os que ja tinhamos
dados_final = pd.concat([dadosModificados,dummie_dados],axis=1)
dados_final.head()


Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn   
0        1            0             0                1      0  \
1        0            0             1                0      0   
2        0            0             1                1      1   
3        0            0             0                0      0   
4        0            0             1                1      1   

   VariasLinhasTelefonicas_Nao  VariasLinhasTelefonicas_SemServicoTelefonico   
0                            0                                             1  \
1                            1                                             0   
2                            1                                             0   
3                            0                                             1   
4                            1                                             0   

   VariasLinhasTelefonicas_Sim  ServicoDeInternet_DSL   
0                            0                      1  \
1                            0                      1   
2                            0                      1   
3                            0                      1   
4                            0                      0   

   ServicoDeInternet_FibraOptica  ServicoDeInternet_Nao  SegurancaOnline_Nao   
0                              0                      0                    1  \
1                              0                      0                    0   
2                              0                      0                    0   
3                              0                      0                    0   
4                              1                      0                    1   

   SegurancaOnline_SemServicoDeInternet  SegurancaOnline_Sim   
0                                     0                    0  \
1                                     0                    1   
2                                     0                    1   
3                                     0                    1   
4                                     0                    0   

   BackupOnline_Nao  BackupOnline_SemServicoDeInternet  BackupOnline_Sim   
0                 0                                  0                 1  \
1                 1                                  0                 0   
2                 0                                  0                 1   
3                 1                                  0                 0   
4                 1                                  0                 0   

   SeguroNoDispositivo_Nao  SeguroNoDispositivo_SemServicoDeInternet   
0                        1                                         0  \
1                        0                                         0   
2                        1                                         0   
3                        0                                         0   
4                        1                                         0   

   SeguroNoDispositivo_Sim  SeguroNoDispositivo_Nao   
0                        0                        1  \
1                        1                        0   
2                        0                        1   
3                        1                        0   
4                        0                        1   

   SeguroNoDispositivo_SemServicoDeInternet  SeguroNoDispositivo_Sim   
0                                         0                        0  \
1                                         0                        1   
2                                         0                        0   
3                                         0                        1   
4                                         0                        0   

   SuporteTecnico_Nao  SuporteTecnico_SemServicoDeInternet   
0                   1                                    0  \
1                   1                                    0   
2                   1                                    0   
3                   

In [22]:
Xmaria = [[0,0,1,1,0,0,39.90,1,0,0,0,1,0,1,0,0,0,0,1,1,1,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,1]]


KNN (K-nearest Neighbors)
Algoritmo de machine learning supervisionado. pode ser usado para tarefas de classificação ou regressão
1.Receber as informações
2.Calcular as distancias
3.ordenar da menor distancia para a maior
4.fazer uma contagem das classes
5.Classificar a partir dos k-vizinhos
6.definir o churn

In [23]:
X=dados_final.drop('Churn',axis=1)
Y=dados_final['Churn']

In [24]:
from sklearn.preprocessing import StandardScaler
norm = StandardScaler()
X_normalizado = norm.fit_transform(X)
X_normalizado[0]

array([ 1.03453023, -0.65401193, -3.05401039,  0.8297975 , -0.96332984,
        3.05401039, -0.85417615,  1.38171215, -0.88565976, -0.52592737,
        1.00669571, -0.52592737, -0.63393298, -0.88361972, -0.52592737,
        1.3782406 ,  1.12942721, -0.52592737, -0.72396752,  1.12942721,
       -0.52592737, -0.72396752,  1.0138687 , -0.52592737, -0.63943864,
        1.2273572 , -0.52592737, -0.79013171,  1.23648892, -0.52592737,
       -0.79607014, -0.56297505,  0.90418382, -0.51424938, -0.52504733,
        1.40641839, -0.54480692, -0.5298852 ])

In [25]:
Xmaria_normalizado = norm.transform(pd.DataFrame(Xmaria,columns=X.columns))
Xmaria_normalizado

array([[-0.96662231, -0.65401193,  0.32743831,  0.8297975 , -0.96332984,
        -0.32743831, 79.93912874,  1.38171215, -0.88565976, -0.52592737,
        -0.99334883,  1.90140322, -0.63393298,  1.13170855, -0.52592737,
        -0.72556272, -0.88540456, -0.52592737,  1.38127743,  1.12942721,
         1.90140322, -0.72396752, -0.98632101,  1.90140322, -0.63943864,
         1.2273572 , -0.52592737, -0.79013171, -0.80874158, -0.52592737,
         1.25617071, -0.56297505, -1.1059698 ,  1.94458183, -0.52504733,
        -0.71102597, -0.54480692,  1.88720123]])

In [26]:
import numpy as np

In [27]:
a = Xmaria_normalizado

In [28]:
b = X_normalizado[0]

In [29]:
a - b

array([[-2.00115254,  0.        ,  3.3814487 ,  0.        ,  0.        ,
        -3.3814487 , 80.79330489,  0.        ,  0.        ,  0.        ,
        -2.00004453,  2.42733059,  0.        ,  2.01532828,  0.        ,
        -2.10380332, -2.01483177,  0.        ,  2.10524495,  0.        ,
         2.42733059,  0.        , -2.00018971,  2.42733059,  0.        ,
         0.        ,  0.        ,  0.        , -2.0452305 ,  0.        ,
         2.05224086,  0.        , -2.01015362,  2.45883121,  0.        ,
        -2.11744436,  0.        ,  2.41708643]])

In [30]:
np.square(a-b)

array([[4.00461149e+00, 0.00000000e+00, 1.14341953e+01, 0.00000000e+00,
        0.00000000e+00, 1.14341953e+01, 6.52755811e+03, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 4.00017814e+00, 5.89193381e+00,
        0.00000000e+00, 4.06154807e+00, 0.00000000e+00, 4.42598840e+00,
        4.05954705e+00, 0.00000000e+00, 4.43205631e+00, 0.00000000e+00,
        5.89193381e+00, 0.00000000e+00, 4.00075888e+00, 5.89193381e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.18296779e+00, 0.00000000e+00, 4.21169253e+00, 0.00000000e+00,
        4.04071758e+00, 6.04585093e+00, 0.00000000e+00, 4.48357062e+00,
        0.00000000e+00, 5.84230682e+00]])

In [31]:
np.sum(np.square(a-b))

6625.894101359011

In [32]:
np.sqrt(6625.894101359011)

81.3995952161865

In [33]:
from sklearn.model_selection import train_test_split
X_treino, X_teste, Y_treino, Y_teste = train_test_split(X_normalizado,Y,test_size=0.3,random_state=123)

In [34]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(metric='euclidean')
knn.fit(X_treino,Y_treino)
predito_knn = knn.predict(X_teste)
predito_knn

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

Teorema de naive Bayer

modelo bernoulli naive bayes
$$
\begin{equation}
    \begin{aligned}
       P(y|X) = \frac{P(X|y) * P(y)}{P(x)} \\
       \\
        P(y|X) &= \text{é a verosimilhança, mede a probabilidade de uma caracteristica acontecer} \\
        P(y) &= \text{probabilidade a priori da classe , prevalença da classe sobre a amostra ( no exemplo atual , qual a chance do churn ser igual a não? )} \\
        P(X) &= \text{probabilidade a priori da evidencia} \\
        P(y|X) &= \text{probabilidade a posteriori} \\

    \end{aligned}
\end{equation}

$$



$$
\begin{aligned}
    P(X) &= \text{ 0.0015 , ou seja a probabilidade da caracteristica "dependentes" ser igual a não é 0.015} \\
    P(y) &= \text{ 0.14 , ou seja a probabilidade de um churn igual a não} \\
    P(X|y) &= \text{ 0.006 , a probabilidade de X dado que Y ocorreu , ou seja a probabilidade de ter um depententes igual a não sendo que o churn é igual a não}\\
    P(y|X) &= \text{? , qual a probabilidade de se ter um churn igual a não sendo que ela tem dependentes igual a não}\\
\end{aligned}
$$



$$
    \begin{equation}
            P(y|X) = \frac{0.006 * 0.14}{0.0015} \\
            \\
            P(y|X) = 0.056 = 5,6%\\
    \end{equation}
$$



multivariada de bernouli

$$
  \begin{equation}
    \begin{aligned}
       P(X_{i}|y) = P(i|y)x_{i} + (1 - P(i|y)) (1 - x_{i})  \\
       \\
        P(i|Y) &= \text{parametro p da distribuição de bernouli | probabilidade de i dado que Y ocorreu} \\
        P(X_{i}) &= \text{conjunto de caracteristicas , no caso temos 38} \\
    \end{aligned}
  \end{equation}

$$

In [35]:

X_treino

array([[-0.96662231, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231,  1.5290241 ,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 ,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023,  1.5290241 , -3.05401039, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ]])

In [37]:
Y_treino

1479    0
2377    0
6613    0
6468    0
2668    1
       ..
5218    0
4060    0
1346    1
3454    0
3582    0
Name: Churn, Length: 4930, dtype: int64

In [ ]:
#escolher usar  mediana
np.median(X_treino)